### ISSUE TITLE
Prioritize environments

### ISSUE THREAD

**Issue by cidthecoatrack** [DnDGen/EncounterGen#2]
There are 780 tables to make (39 environments, 20 levels each), which is a lot.  I want to prioritize the environments so I can release this module in phases.

The environments are:

1. Dungeon
2. Civilized (Night and Day)
3. Desert (Warm, Temperate, Cold) (Night and Day)
4. Forest (Warm, Temperate, Cold) (Night and Day)
5. Plains (Warm, Temperate, Cold) (Night and Day)
6. Hills (Warm, Temperate, Cold) (Night and Day)
7. Mountains (Warm, Temperate, Cold) (Night and Day)
8. Marsh/Swamp (Warm, Temperate, Cold) (Night and Day)

We can prioritize any way we want (maybe temperate before cold, hills before mountains), but I am going to insist on Night and Day for whatever we choose.

**Comment by cidthecoatrack** [comment]
I have currently completed 36 environments so far

**Comment by cidthecoatrack** [comment]
Tables completed:
* Level 11 Civilized Night
* Level 4 Cold Desert Day
* Level 6 Temperate Desert Night
* Level 1 Warm Desert Night
* Dungeon levels 1, 2, 4, 5, 12, 15, 16, 18-20
* Level 20 Temperate Forest Day
* Level 18 Temperate Forest Night
* Level 8 Warm Forest Day
* Level 2 Warm Forest Night
* Cold Hills Day levels 15, 19
* Cold Hills Night levels 14, 19
* Level 6 Temperate Hills Day
* Level 7 Warm Hills Day
* Level 7 Warm Hills Night
* Level 18 Cold Marsh Day
* Temperate Marsh Day levels 19, 20
* Level 18 Temperate Marsh Night
* Warm Marsh Day levels 8, 17
* Level 11 Cold Mountain Night
* Level 20 Temperate Mountain Night
* Level 4 Cold Plains Day
* Temperate Plains Night level 9, 20

**Comment by aloisdg** [comment]
Could you write  a "how to build one"? (or show where to look)

**Comment by cidthecoatrack** [comment]
It is something of a complicated process, but I will try to put some instructions in here:

1. Dungeons are generated according to the tables provided in the 3.0 (**NOT** 3.5) Dungeon Master's Guide.
2. Non-civilized environments are generated according to the information in the excel file included in the project.
   A. Each environment/temperature combination has its own sheet
   B. In each sheet, you can sort by the EL (Encounter Level), which should group all encounters by their level
   C. On some of the sheets, you will see numbers next to the encounters, all under Night and Day columns.  These indicate the abstract likelihood of that encounter occurring.  The likelihood is determined by where the encounter originates from.
      I. Any encounter that is specific to that environment (a blank space) is a 3.
      II. Anything that is generic for an environment (all land, all desert, all warm, etc. - marked by L for land, D for desert, F for forest, C for cold, etc.) is a 2
      III. Anything that is a Haunted/Magical creature (marked HM) is a 1
      IV. In addition to these numbers, there are certain extra encounters (such as character parties) that can be encountered at any level.  These are at the bottom of te list of encounters, as their EL is marked as "EL"
      V. If you are making a Day encounter table, put a 0 for creatures that will not appear in the day (such as Shadows or Vampires)
      VI. Sum up these numbers per the level you are trying to build.  Use that sum to determine how much each abstract amount equates to in percentage points.  For instance, if the sum for a level is 50, then each amount is worth 2 percentage points (so an HM would be 1-2, an L 3-6, and specific 9-14, as a random example).  Several tables have these sum/percentage points formulas entered into Excel.
   D. There is a lot of ad-hoc things that have to be done in addition to this
      I. If level 20, there are additional character party encounters (see any of the Level 20 encounter tables)
      II. Zombies can only be encountered up to level 14
      III. Skeletons can only be encountered up to level 16
      IV. The quantity for Zombies, Skeletons, Celestial Creatures, and Fiendish Creatures do not matter (they will be redetermined by the generated base creatures)
      V. Sometimes the relative amounts need to be adjusted, so that the table pans out evenly.  Changing 1/2/3 to 1/3/5 can be helpful, or other adjustments until it comes very close to evenly distributed.
      VI. Any extra percentage points, assign to the Character party of 1d3+1
      VII. Civilized encounters are slightly more complicated, since their EL depends on the character levels.  The descriptions for the encounters should say what range is good, but if more clarification is needed, it can be further explained.

The tables should be formatted in the XML files, as demonstrated in the projects.  Write tests to verify the table contents, as shown in the EncounterGen.Tests.Integration.Tables project.

In the end, if you want to try your hand at building a table, @aloisdg, make a pull request and I would be glad to review it.  However, if that seems a bit daunting (which I completely understand), another useful thing could be to give your opinion on a useful priority of environments - which environment you want to see first in a beta, which environments could be pushed off to full releases (or maybe even 2.0)

**Comment by cidthecoatrack** [comment]
Dungeon environments are done as of version 0.1.  Here is a list of environments (to be updated as they are completed, 20 levels each)

- [x] Dungeon
- [ ] Civilized
    - [ ] Day
    - [ ] night
- Desert
    - [ ] Warm
        - [ ] Day
        - [ ] night
    - [ ] Temperate
        - [ ] Day
        - [ ] night
    - [ ] Cold
        - [ ] Day
        - [ ] night
- [ ] Forest
    - [ ] Warm
        - [ ] Day
        - [ ] night
    - [ ] Temperate
        - [ ] Day
        - [ ] night
    - [ ] Cold
        - [ ] Day
        - [ ] night
- [ ] Hills
    - [ ] Warm
        - [ ] Day
        - [ ] night
    - [ ] Temperate
        - [ ] Day
        - [ ] night
    - [ ] Cold
        - [ ] Day
        - [ ] night
- [ ] Mountain
    - [ ] Warm
        - [ ] Day
        - [ ] night
    - [ ] Temperate
        - [ ] Day
        - [ ] night
    - [ ] Cold
        - [ ] Day
        - [ ] night
- [ ] Plain
    - [ ] Warm
        - [ ] Day
        - [ ] night
    - [ ] Temperate
        - [ ] Day
        - [ ] night
    - [ ] Cold
        - [ ] Day
        - [ ] night
- [ ] Marsh/Swamp
    - [ ] Warm
        - [ ] Day
        - [ ] night
    - [ ] Temperate
        - [ ] Day
        - [ ] night
    - [ ] Cold
        - [ ] Day
        - [ ] night

**Comment by cidthecoatrack** [comment]
Civilized (Day and Night) done as of `v0.2-beta`
